# fly.toml app configuration file generated for read-mando on 2025-02-16T11:52:27-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'read-mando'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
