import { useEffect, useState } from "react";
import axios from "axios";
import PropTypes from "prop-types";
import AudioPlayer from "../components/AudioPlayer";
import { Link } from "react-router-dom";

export default function ReviewPage({ user, loadingUser }) {
  const [stories, setStories] = useState([]);
  const [error, setError] = useState("");
  const apiUrl = import.meta.env.VITE_API_BASE_URL;

  useEffect(() => {
    fetchStories();
  }, []);

  const fetchStories = async () => {
    setError("");
    try {
      const res = await axios.get(`${apiUrl}/stories/all`);
      setStories(res.data);
    } catch (err) {
      setError("Failed to load stories.");
    }
  };

  const handleUpvote = async (story_id) => {
    if (!user.user_id) {
      alert("Please log in to upvote stories!");
    } else {
      try {
        const res = await axios.put(`${apiUrl}/stories/${story_id}/toggle-upvote`, {}, { withCredentials: true });
        setStories(prev => prev.map(s => s.story_id === story_id ? { ...s, upvotes: res.data.upvotes } : s));
      } catch (err) { console.error(err); }
    }
  };

  const cardStyle = `
    bg-white dark:bg-gray-800 p-8 rounded-2xl border-4 border-gray-900 dark:border-white/10
    shadow-[4px_4px_0_0_rgba(0,0,0,1)] dark:shadow-[4px_4px_0_0_rgba(255,255,255,0.05)]
    hover:translate-y-[-4px] hover:shadow-[8px_8px_0_0_rgba(0,0,0,1)] dark:hover:shadow-[8px_8px_0_0_rgba(255,255,255,0.1)]
    transition-all duration-300 flex flex-col group
  `;

  if (loadingUser) return <div className="flex justify-center items-center py-20 font-black dark:text-white uppercase tracking-widest animate-pulse text-2xl">Loading the Hub...</div>;

  return (
    <div className="px-6 py-12 max-w-7xl mx-auto pb-20">
      <div className="mb-12 text-center fade-up">
        <h1 className="text-4xl md:text-5xl font-black tracking-tight text-gray-900 dark:text-white mb-4">
          Community <span className="text-blue-600">Hub</span>
        </h1>
        <p className="text-gray-500 dark:text-gray-400 font-medium max-w-2xl mx-auto">
          Explore and read stories generated by other learners. Upvote your favorites!
        </p>
      </div>

      {error && <div className="text-center p-8 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded-2xl border-4 border-red-200 dark:border-red-900/30 font-bold mb-8">{error}</div>}

      {stories.length === 0 && !loadingUser && (
        <div className="text-center py-20 opacity-20">
          <div className="text-6xl mb-4">📭</div>
          <p className="text-xl font-black dark:text-white">No stories shared yet. Be the first!</p>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {stories.map((story, idx) => (
          <div key={story.story_id} className={`${cardStyle} fade-up`} style={{ animationDelay: `${(idx % 6) * 100}ms` }}>
            <div className="flex justify-between items-start mb-6">
              <div className="max-w-[70%]">
                <h2 className="text-2xl font-black text-gray-900 dark:text-white mb-1 group-hover:text-blue-600 transition-colors truncate">
                  {story.title}
                </h2>
                <p className="text-[10px] font-black uppercase tracking-widest text-gray-400">
                  by {story.user_stories?.[0]?.users?.username || "Guest"}
                </p>
              </div>
              <button
                onClick={() => handleUpvote(story.story_id)}
                className="flex items-center gap-2 px-3 py-1.5 rounded-xl border-2 border-gray-900 dark:border-white/20 bg-pink-50 dark:bg-pink-900/20 text-pink-600 font-black shadow-[2px_2px_0_0_rgba(0,0,0,1)] hover:translate-y-[-1px] active:translate-y-[1px] active:shadow-none transition-all cursor-pointer"
              >
                👍 {story.upvotes || 0}
              </button>
            </div>

            <p className="text-gray-600 dark:text-gray-300 font-medium mb-6 line-clamp-3 leading-relaxed">
              {story.content}
            </p>

            <div className="flex flex-wrap gap-2 mb-8 mt-auto">
              {story.vocabulary?.slice(0, 4).map((word, vIdx) => (
                <span key={vIdx} className="bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400 text-[10px] font-black px-2 py-1 rounded-md border border-blue-100 dark:border-blue-900/30 uppercase tracking-wider">
                  {word}
                </span>
              ))}
              {story.vocabulary?.length > 4 && (
                <span className="text-[10px] font-black text-gray-400 px-2 py-1">+{story.vocabulary.length - 4} more</span>
              )}
            </div>

            <div className="space-y-4 mb-8">
              <div className="p-3 bg-gray-50 dark:bg-gray-900/50 rounded-xl border-2 border-gray-900 dark:border-white/10">
                <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-2">Narrator Audio</p>
                <AudioPlayer audioUrl={story.story_audio} />
              </div>
            </div>
            
            <Link 
              to={`/story/${story.story_id}`}
              className="w-full py-3 bg-gray-900 dark:bg-white dark:text-gray-900 text-white font-black rounded-xl text-center hover:bg-blue-600 dark:hover:bg-blue-400 dark:hover:text-white transition-all shadow-lg"
              state={{story}}
            >
              Read Full Story →
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
}

ReviewPage.propTypes = {
  user: PropTypes.object,
  loadingUser: PropTypes.bool,
};
